config/routes.rb
Rails.application.routes.draw do

  resources :posts
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'home#index'
  get 'privacy' => 'home#privacy'
  
  
  # mount ActionCable.server => '/cable'
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: "users/passwords",
    invitations: 'users/invitations'
  }
  devise_scope :user do
    get '/revoke_login/:uid/:provider' => 'users/omniauth_callbacks#revoke_login', as: :revoke_login
  end
  resources :companies, except: %i[new create] do
    collection do
      get :signup, path: 'sign_up'
      post :register
    end
  end

  post 'file/receive' => 'file#receive'
  get '/dashboard' => 'home#dashboard', as: :dashboard

  namespace :api, defaults: {format: 'json'} do

    namespace :v1 do
      # match "/404" => "errors#not_found"
      # match "/500" => "errors#exception"
      #root to: 'dash#index', default: {format: 'html'}
      get 'items/:account_id' => 'items#account_items'
      resources :accounts
      resources :users
      get 'analytics/campaign_date_ranges', to: 'analytics#campaign_date_ranges'
      get 'analytics/campaign_results/:account_id/:campaign_id', to: 'analytics#campaign_results'
      get 'analytics/ranges', to: 'analytics#analytics_range'
      delete 'analytics/ranges/:range_id', to: 'analytics#delete_range'
      put 'analytics/ranges/:range_id', to: 'analytics#update_range'
      post 'analytics/ranges', to: 'analytics#create_analytics_range'
      get 'analytics/twitter_campaign/:account_id/:campaign_id', to: 'analytics#get_twitter_campaign_calculations'
      get 'analytics/twitter_campaign_calculations/:account_id', to: 'analytics#twitter_campaign_calculations'
      get 'analytics/timezones', to: 'analytics#timezones'
      get 'analytics/twitter_ad_hoc/:keyword_id/:from/:to/:time_zone', to: 'analytics#twitter_analytics_ad_hoc'
      get 'analytics/twitter_campaign_ad_hoc/:campaign_id/:from/:to/:time_zone', to: 'analytics#twitter_by_campaign_ad_hoc'
      get 'analytics/:account_id', to: 'analytics#index'
      post 'analytics/:account_id', to: 'analytics#create'
      post 'analytics/:account_id/query/:query_id', to: 'analytics#query'
      get 'analytics/tweets_hourly_distribution/:keyword_id/:from/:to/:time_zone', to: 'analytics#tweets_hourly_distribution'
      post 'organizations/create/:account_id' => 'organizations#create'
      get 'organizations/:account_id/:organization_id', to: 'organizations#show'
      get 'organizations/:account_id' => 'organizations#index'
      put 'organizations/:account_id/:organization_id' => 'organizations#update'
      get 'aggregate_results/:acc/:orgid' => 'aggregate_results#show'
      resources :aggregate_results # using Apphera aggregation framework
      get 'campaigns/:account_id' => 'campaigns#index'
      post 'campaigns/:account_id' => 'campaigns#create'
      post 'campaigns/:account_id/keywords/:campaign_id' => 'campaigns#add_keywords'
      put 'campaigns/:account_id/:campaign_id/edit' => 'campaigns#edit'
      put 'campaigns/:account_id/keywords/:campaign_id' => 'campaigns#update_keywords'
      delete 'campaigns/:account_id/:campaign_id' => 'campaigns#destroy'
      get 'categories/:id' => 'categories#show'
      get 'categories' => 'categories#index'
      resources :countries
      get 'competitors/:acc/:id' => 'competitors#show'
      get 'reviews/crawl/:account_id/:organization_id' => 'reviews#crawl'
      post 'facebook/pages/settings' => 'facebook#pages_settings'
      post 'facebook/post', to: 'facebook#facebook_post'
      post 'facebook/pages/credentials', to: 'facebook#set_page_credentials'
      post 'facebook/pages/credentials_short', to: 'facebook#set_page_credentials_short_token'
      post 'facebook/pages/credentials/:account_id/:c_user_id', to: 'facebook#set_page_credentials_from_c_user'
      post 'facebook/pages/post', to: 'facebook#page_post'
      post 'facebook/users/credentials', to: 'facebook#set_credentials'
      get 'facebook/users/credentials/:account_id', to: 'facebook#get_all_credentials'
      get 'facebook/users/credentials/:account_id/:c_user_id', to: 'facebook#get_credentials'
      delete 'facebook/users/credentials/:account_id/:c_user_id', to: 'facebook#delete_credentials'
      get 'facebook/pages/credentials/:account_id', to: 'facebook#get_page_credentials'
      get 'facebook/pages/credentials/:account_id/:c_user_id', to: 'facebook#get_page_credentials_by_user'
      delete 'facebook/pages/credentials/:account_id/:fb_id', to: 'facebook#delete_page_credentials'
      get 'facebook/pages/read_wall/:account_id/:fb_id', to: 'facebook#read_wall'
      get 'facebook/pages/read_wall_comments/:account_id/:fb_id', to: 'facebook#read_wall_comments'
      delete 'facebook/pages/posts/:account_id/:fb_id/:post_id', to: 'facebook#delete_post'
      post 'facebook/pages/posts/comment', to: 'facebook#post_comment'
      post 'facebook/pages/comments/reply', to: 'facebook#reply_to_comment'
      delete 'facebook/pages/comments/:account_id/:fb_id/:comment_id', to: 'facebook#delete_comment'
      get 'rankings/:id' => 'rankings#index'
      get 'reviewers/:id/reviews' => 'reviewers#reviewer_reviews'
      get 'reviewers/:id' => "reviewers#show"
      get 'reviews/:account_id/:organization_id' => 'reviews#show'
      resources :content_providers
      resources :geocomps
resources :contents  
    get 'sentiments/languages' => 'sentiments#languages'
      get 'sentiments/:lang/:body' => 'sentiments#show'
      get 'senti/positive' => 'senti#positive'
      get 'senti/negative' => 'senti#negative'
      get 'senti/neutral' => 'senti#neutral'
      post 'senti/classify' => 'senti#classify'
      post 'senti/train' => 'senti#train'
      post 'senti/untrain' => 'senti#untrain'
      post 'sentiments' => 'sentiments#complex'
      post 'behavior/classify' => 'behavior#classify'
      post 'behavior/train' => 'behavior#train'
      post 'behavior/untrain' => 'behavior#untrain'
      get 'tracks' => 'tracks#index'
      get 'tracks/:keyword_id/facebook' => 'tracks#facebook'
      get 'tracks/:keyword_id/youtube' => 'tracks#youtube'
      get 'tracks/:keyword_id/instagram' => 'tracks#instagram'
      get 'tracks/:keyword_id/search/:market' => 'tracks#search'
      get 'tracks/:keyword_id/twitter' => 'tracks#twitter'

      resources :schedules
      # post 'keywords/:account_id/:keyword' => 'keywords#create_for_account'
      # post 'keywords/:acc/:org/:keyword' => 'keywords#create'
      post 'keywords/:account_id' => 'keywords#create_for_account'
      #post 'keywords/:acc/:org/' => 'keywords#create'
      delete 'keywords/:acc/:org/:keyword_id' => 'keywords#delete_association'
      get 'keywords/:acc/' => 'keywords#keywords_by_account'
      get 'keywords/refresh/:keyword_id' => 'keywords#refresh_aggregates'
      get 'keywords/:acc/:org' => 'keywords#index'
      get 'links/:acc/:org' => 'links#index'
      get 'markets' => 'markets#index'
      resources :instagram
      get 'google_plus/people/search/:p' => 'google_plus#people_search'
      #get 'google_plus/:acc/people/search/:p' => 'google_plus#people_search'
      get 'google_plus/people/:id/track' => 'google_plus#people_track'
      get 'google_plus/people/:id/activities' => 'google_plus#people_activities'
      get 'google_plus/people/:id/untrack' => 'google_plus#people_untrack'
      get 'google_plus/activity/:id/plusones' => 'google_plus#activity_plusones'
      get 'google_plus/activity/:id/reshares' => 'google_plus#activity_reshares'
      get 'google_plus/activity/:id/comments' => 'google_plus#activity_comments'
      resources :google
      get 'twitter/app/credentials' => 'twitter#get_app_credentials'
      post 'twitter/app/credentials' => 'twitter#set_app_credentials'
      delete 'twitter/app/credentials' => 'twitter#delete_app_credentials'
      put 'twitter/app/credentials' => 'twitter#update_app_credentials'
      post 'twitter/tweet' => 'twitter#tweet'
      post 'twitter/credentials' => 'twitter#set_credentials'
      get 'twitter/user/:user_id/tweets' => 'twitter#user_tweets'
      get 'twitter/search/:search' => 'twitter#tweet_search'
      get 'twitter/followers_average' => 'twitter#followers_average'
      get 'twitter/followers_count' => 'twitter#followers_count'
      get 'twitter/users_count' => 'twitter#users_count'
      get 'twitter/newest' => 'twitter#newest'
      get 'twitter/timeline/:c_user_id' => 'twitter#read_timeline'
      resources :twitter #wrap apphera twitter API
    
      resources :apps, only: %i[index]
    end
  end
end

app/views/apps/_form.html.erb
<div class="ibox float-e-margins">
  <div class="ibox-title">
    <h5>Form</h5>
  </div>
  <div class="ibox-content">
    <%= form_with(model: app, local: true, html: {class: 'form-horizontal'}) do |f| %>
      <div class="form-group">
        <%= f.label :name, 'Name&nbsp;<span class="require_icn">*</span>'.html_safe, class: 'control-label col-lg-2' %>
        <div class="col-lg-10">
          <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
          <div class='error'><%= display_error_messages app.errors, [:name] %></div>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :title, class: 'control-label col-lg-2' %>
        <div class="col-lg-10">
          <%= f.text_field :title, class: 'form-control', placeholder: 'Become the most awesome something' %>
          <div class='error'><%= display_error_messages app.errors, [:title] %></div>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :category_id, class: 'col-lg-2 control-label' %>
        <div class="col-lg-10">
          <%= f.select :category_id, options_for_select(Category.order(:id).map{|t| [t.name, t.id]}, f.object.category_id), {include_blank: true}, {class: 'form-control'}  %>
          <div class='error'><%= display_error_messages app.errors, [:category, :category_id] %></div>
        </div>
      </div>
      
      <div class="form-group">
        <%= f.label :app_id, class: 'control-label col-lg-2' %>
        <div class="col-lg-10">
          <%= f.text_field :app_id, class: 'form-control', placeholder: 'App Id' %>
          <div class='error'><%= display_error_messages app.errors, [:app_id] %></div>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :description, class: 'control-label col-lg-2' %>
        <div class="col-lg-10">
          <%= f.text_field :description, class: 'form-control', placeholder: 'Description' %>
          <div class='error'><%= display_error_messages app.errors, [:description] %></div>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :is_hawk, class: 'control-label col-lg-2' %>
        <div class="col-lg-10">
          <%= f.check_box :is_hawk, class: 'form-control', placeholder: 'is_hawk' %>
          <div class='error'><%= display_error_messages app.errors, [:is_hawk] %></div>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :coming_soon, class: 'control-label col-lg-2' %>
        <div class="col-lg-10">
          <%= f.check_box :coming_soon, class: 'form-control', placeholder: 'is_hawk' %>
          <div class='error'><%= display_error_messages app.errors, [:coming_soon] %></div>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :commercial, class: 'control-label col-lg-2' %>
        <div class="col-lg-10">
          <%= f.check_box :commercial, class: 'form-control', placeholder: 'is_hawk' %>
          <div class='error'><%= display_error_messages app.errors, [:commercial] %></div>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :public, class: 'control-label col-lg-2' %>
        <div class="col-lg-10">
          <%= f.check_box :public, class: 'form-control', placeholder: 'public' %>
          <div class='error'><%= display_error_messages app.errors, [:public] %></div>
        </div>
      </div>
     
      <div class="form-group">
        <%= f.label :image, class: 'col-lg-2 control-label' %>
        <div class="col-lg-10">
          <%= f.file_field :image, class: 'form-control', accept: 'image/png,image/gif,image/jpeg' %>
          <div class='error'><%= display_error_messages app.errors, [:image] %></div>
          <% if !f.object.new_record? %>
            <% if app.image? %>
              <br>
              <%= link_to f.object.image.url, target: '_blank' do %>
                <%= image_tag(app.image.url, class: 'img-responsive img-thumbnail') %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :password, class: 'control-label col-lg-2' %>
        <div class="col-lg-10">
          <%= f.text_field :password, class: 'form-control', placeholder: 'Password' %>
          <div class='error'><%= display_error_messages app.errors, [:password] %></div>
        </div>
      </div>
      <div class="hr-line-dashed"></div>
      <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10">
          <%= f.submit class: 'btn btn-sm btn-white', data: {disable_with: 'Please Wait...'} %>
          <%= link_to 'Cancel', apps_url, class: 'btn btn-sm btn-danger', data: {disable_with: 'Please Wait...'} %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/apps/backup_public_app.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-sm-4">
    <h2>Public Apps</h2>
    <%= render_breadcrumbs %>
  </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class='row'>
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h5>Public Apps</h5>
      </div>
      <div class="ibox-content">
        <% if @public_apps.present? %>
          <table class="table table-hover">

            <thead>
              <tr>
                <th>Name</th>
                <th>Action</th>
              </tr>
            </thead>

            <tbody>
              <% @public_apps.each do |app| %>
                <tr>
                  <td><%= app.name %></td>
                  <td>
                    <%= link_to 'Quiz', public_quiz_concept_path(app.id), class: 'btn btn-xs btn-default' if app.concepts.present? %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% else %>
          <p>No Apps Found </p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/apps/concepts.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-sm-4">
    <h2>List Concepts</h2>
    <%= render_breadcrumbs %>
  </div>
  <div class="col-sm-8 text-right">
  </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
  <div class='row'>
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h5>List Concepts</h5>
      </div>
      <div class="ibox-content">
        <% if @concepts.present? %>
          <table class="table table-hover">

            <thead>
              <tr>
                <th>Title</th>
                <th>Body</th>
                <th>Language</th>
                <th>App</th>
                <th>Points</th>
              </tr>
            </thead>

            <tbody>
              <% @concepts.each do |concept| %>
                <tr>
                  <td><%= concept.title %></td>
                  <td class="col-sm-6"><%= concept.body %></td>
                  <td><%= concept.try(:language).try(:country) %></td>
                  <td><%= concept.try(:app).try(:name) %></td>
                  <td>
                    <% if concept.answers.present? %>
                      <span class='badge badge-success'><%= concept.answers.where(user_id: current_user.id).sum(:points) %></span>
                    <% else %>
                      <%= link_to 'Quiz', quiz_concept_path(concept), class: 'btn btn-xs btn-default' %>
                    <% end %>
                    <%#= link_to concept, class: 'btn btn-xs btn-default' do %>
                      <!-- <i class="fa fa-eye"></i> -->
                    <%# end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% else %>
          <p>No Concepts Found </p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/apps/edit.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-sm-4">
    <h2>Editing Apps</h2>
    <%= render_breadcrumbs %>
  </div>
  <div class="col-sm-8 text-right">
    <p class='add-record text-right'>
      <%= link_to apps_url, data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Loading...".html_safe} do %>
        <i class="fa fa-list"></i> List Apps
      <% end %>
    </p>
  </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-8">
      <%= render 'form' %>
    </div>
    <div class="col-lg-4">  title description badge</div>
    <div class="clearfix"></div>
  </div>
</div>

app/views/apps/enjoy_badge.html.erb
You did it! enjoy <%= @badge.title %>

app/views/apps/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-sm-4">
    <h2>Apps</h2>
    <%= render_breadcrumbs %>
  </div>
  <div class="col-sm-8 text-right">
    <p class='add-record text-right'>
      <% if current_user.is_company_or_admin_access? %>
        <%= link_to new_app_path, data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Loading...".html_safe} do %>
          <i class="fa fa-plus"></i> Add New Apps
        <% end %>
      <% end %>
    </p>
  </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class='row'>
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h5>List Apps</h5>
      </div>
      <div class="ibox-content">
        <% if apps.present? %>
          <table class="table table-hover">

            <thead>
              <tr>
                <th>Name</th>
                <th></th>
              </tr>
              <tr>
                <th>Category</th>
                <th></th>
              </tr>
            </thead>

            <tbody>
              <% apps.each do |app| %>
                <tr>
                  <td><%= link_to app.name, concepts_app_path(app.id), data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Loading...".html_safe} %></td>
                  <td>
                    <!-- <span class="badge badge-primary pull-right <%#= app.concepts.present? ? '' : 'hide' %> " data-trigger="hover" data-container="body" data-toggle="popover" data-placement="left" data-content="Associated <%#= 'Concept'.pluralize(app.concepts.count) %>">
                      <%#= app.concepts.count %>
                    </span> -->
                    <% if current_user.is_company_or_admin_access? %>
                      <%= link_to app, class: 'btn btn-xs btn-default' do %>
                        <i class="fa fa-eye"></i>
                      <% end %>
                      <%= link_to edit_app_path(app), class: 'btn btn-xs btn-default' do %>
                        <i class="fa fa-pencil"></i>
                      <% end %>
                      <%= link_to app, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-default' do %>
                        <i class="fa fa-trash"></i>
                      <% end %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>

          </table>
        <% else %>
          <p>No Apps Found </p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/apps/new.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-sm-4">
    <h2>Add New Apps</h2>
    <%= render_breadcrumbs %>
  </div>
  <div class="col-sm-8 text-right">
    <p class='add-record text-right'>
      <%= link_to apps_url, data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Loading...".html_safe} do %>
        <i class="fa fa-list"></i> List Apps
      <% end %>
    </p>
  </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-8">
      <%= render 'form' %>
    </div>
    
    <div class="clearfix"></div>
  </div>
</div>

app/views/apps/public_app.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-sm-4">
    <h2>Public Apps</h2>
    <%= render_breadcrumbs %>
  </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
        <% @public_apps.each do |app| %>
          
            <div class="col-lg-3">
                <div class="contact-box center-version">

                    <a href="https://www.eqbotics.com/public_quiz_concept/<%= app.id %>">

                        <img alt="image" class="img-circle" src="https://www.eqbotics.com<%= app.badge.img.url %>">


                        <h3 class="m-b-xs"><strong><%= app.title %></strong></h3>

                        <div class="font-bold"><%= app.description %></div>
                        <address class="m-t-md">
                            <strong>Get the Badge named:</strong><br>
                           <%= app.badge.title %><br>
                            
                        </address>

                    </a>
                    

                </div>

            </div>
<% end %>

</div></div>

app/views/apps/public_index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-sm-4">
    <h2>Apps</h2>
  </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <% @apps.each do |app| %>
      <div class="col-lg-3">
        <div class="contact-box center-version">
          <a href="#">
            <% if app.image.present? %>
              <%= image_tag(app.image_url, class: 'img-circle') %>
            <% else %>
              <img src="https://placeholdit.co//i/200x200?fc=111111&text=No%20Image%20Found", class='img-circle'>
            <% end %>
            <h3 class="m-b-xs"><strong><%= app.name %></strong></h3>
            <div class="font-bold"><%= app.title %></div>
            <address class="m-t-md">
              <strong><%= app.description %></strong>
            </address>
          </a>
          <div class="contact-box-footer">
            <div class="m-t-xs btn-group">
              <a class="btn btn-xs btn-white"><i class="fa fa-thumbs-up"></i>YES! I am in!</a>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/apps/public_quiz_concept.html.erb
<% concept = @concept %>

<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-sm-4">
    <h2>Public Quiz for - <%= @app.name %></h2>
    <%#= render_breadcrumbs %>
  </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class='row'>
    <div class='col-lg-2'></div>

    <div class='col-lg-8'>
      <div class='ibox float-e-margins'>
        <div class='ibox-content'>
          <div class='table-responsive'>
            <h2><b><%= concept.try(:title) %> (<%= @concept_number%>/<%= @app_concepts_count%>)</b></h2>
            <% if concept.image? %>
              <%= link_to concept.image.url, target: '_blank' do %>
                <%= image_tag(concept.image.url, class: 'img-responsive img-thumbnail') %>
              <% end %>
            <% end %>
            <div>
              <h4>Description</h4>
              <%= concept.body.html_safe %>
            </div>
            <div>
              <h2><strong>Quiz</strong></h2>
            </div>
            <div>
              <h4>Question</h4>
              <%= concept.question %>
            </div>
            <%= form_tag submit_public_quiz_concept_path(concept), method: :post do %>
            <%= hidden_field_tag 'app_id', params[:app_id] %>
              <%# ['answer1', 'answer2', 'answer3', 'answer4'].each_with_index do |ans, index| %>
              <% ['answer1', 'answer2', 'answer3', 'answer4'].each_with_index do |ans, index| %>
                <div>
                  <%= radio_button_tag 'correct_answer', ans, index == 0 ? true : false %>
                  <%= concept.send(ans.to_sym) %>
                </div>
              <% end %>
              <hr>
              <div>
                <%= submit_tag 'Submit Your Answer', class: 'btn btn-primary' %>
              </div>
            <% end %>
         	</div>
        </div>
      </div>
    </div>

    <div class='col-lg-2'></div>
  </div>
</div>

app/views/apps/show.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-sm-4">
    <h2>View App</h2>
    <%= render_breadcrumbs %>
  </div>
  <div class="col-sm-8 text-right">
    <p class='add-record text-right'>
      <%= link_to apps_url, data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Loading...".html_safe} do %>
        <i class="fa fa-list"></i> List App
      <% end %>
    </p>
  </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class='row'>
    <div class='col-lg-12'>
      <div class='ibox float-e-margins'>
        <div class='ibox-content'>
          <div class='table-responsive'>
            <% if app %>
  			      <%= link_to new_app_path, data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Loading...".html_safe} do %>
  			        <i class="fa fa-plus"></i> Add App
  			      <% end %>
  			      &nbsp;&nbsp;
  			      <%= link_to edit_app_path(app), data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Loading...".html_safe} do %>
  			        <i class="fa fa-pencil"></i> Edit App
  			      <% end %>

              <table class='table table-bordered table-hover'>
                <tr>
                  <td class="col-lg-3">ID</td>
                  <td><%= app.id %></td>
                </tr>
                <tr>
                  <td class="col-lg-3">Name</td>
                  <td><%= app.name %></td>
                </tr>
                <tr>
                  <td class="col-lg-3">Created At</td>
                  <td><%= local_time(app.created_at) %></td>
                </tr>
                <tr>
                  <td class="col-lg-3">Updated At</td>
                  <td><%= local_time(app.updated_at) %></td>
                </tr>
              <% end %>
            </table>

         	</div>
        </div>
      </div>
    </div>
  </div>
</div>