config/routes.rb
Rails.application.routes.draw do

  resources :posts
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'home#index'
  get 'privacy' => 'home#privacy'
  
  
  # mount ActionCable.server => '/cable'
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: "users/passwords",
    invitations: 'users/invitations'
  }
  devise_scope :user do
    get '/revoke_login/:uid/:provider' => 'users/omniauth_callbacks#revoke_login', as: :revoke_login
  end
  resources :companies, except: %i[new create] do
    collection do
      get :signup, path: 'sign_up'
      post :register
    end
  end

  post 'file/receive' => 'file#receive'
  get '/dashboard' => 'home#dashboard', as: :dashboard

  namespace :api, defaults: {format: 'json'} do

    namespace :v1 do
      # match "/404" => "errors#not_found"
      # match "/500" => "errors#exception"
      #root to: 'dash#index', default: {format: 'html'}
      get 'items/:account_id' => 'items#account_items'
      resources :accounts
      resources :users
      get 'analytics/campaign_date_ranges', to: 'analytics#campaign_date_ranges'
      get 'analytics/campaign_results/:account_id/:campaign_id', to: 'analytics#campaign_results'
      get 'analytics/ranges', to: 'analytics#analytics_range'
      delete 'analytics/ranges/:range_id', to: 'analytics#delete_range'
      put 'analytics/ranges/:range_id', to: 'analytics#update_range'
      post 'analytics/ranges', to: 'analytics#create_analytics_range'
      get 'analytics/twitter_campaign/:account_id/:campaign_id', to: 'analytics#get_twitter_campaign_calculations'
      get 'analytics/twitter_campaign_calculations/:account_id', to: 'analytics#twitter_campaign_calculations'
      get 'analytics/timezones', to: 'analytics#timezones'
      get 'analytics/twitter_ad_hoc/:keyword_id/:from/:to/:time_zone', to: 'analytics#twitter_analytics_ad_hoc'
      get 'analytics/twitter_campaign_ad_hoc/:campaign_id/:from/:to/:time_zone', to: 'analytics#twitter_by_campaign_ad_hoc'
      get 'analytics/:account_id', to: 'analytics#index'
      post 'analytics/:account_id', to: 'analytics#create'
      post 'analytics/:account_id/query/:query_id', to: 'analytics#query'
      get 'analytics/tweets_hourly_distribution/:keyword_id/:from/:to/:time_zone', to: 'analytics#tweets_hourly_distribution'
      post 'organizations/create/:account_id' => 'organizations#create'
      get 'organizations/:account_id/:organization_id', to: 'organizations#show'
      get 'organizations/:account_id' => 'organizations#index'
      put 'organizations/:account_id/:organization_id' => 'organizations#update'
      get 'aggregate_results/:acc/:orgid' => 'aggregate_results#show'
      resources :aggregate_results # using Apphera aggregation framework
      get 'campaigns/:account_id' => 'campaigns#index'
      post 'campaigns/:account_id' => 'campaigns#create'
      post 'campaigns/:account_id/keywords/:campaign_id' => 'campaigns#add_keywords'
      put 'campaigns/:account_id/:campaign_id/edit' => 'campaigns#edit'
      put 'campaigns/:account_id/keywords/:campaign_id' => 'campaigns#update_keywords'
      delete 'campaigns/:account_id/:campaign_id' => 'campaigns#destroy'
      get 'categories/:id' => 'categories#show'
      get 'categories' => 'categories#index'
      resources :countries
      get 'competitors/:acc/:id' => 'competitors#show'
      get 'reviews/crawl/:account_id/:organization_id' => 'reviews#crawl'
      post 'facebook/pages/settings' => 'facebook#pages_settings'
      post 'facebook/post', to: 'facebook#facebook_post'
      post 'facebook/pages/credentials', to: 'facebook#set_page_credentials'
      post 'facebook/pages/credentials_short', to: 'facebook#set_page_credentials_short_token'
      post 'facebook/pages/credentials/:account_id/:c_user_id', to: 'facebook#set_page_credentials_from_c_user'
      post 'facebook/pages/post', to: 'facebook#page_post'
      post 'facebook/users/credentials', to: 'facebook#set_credentials'
      get 'facebook/users/credentials/:account_id', to: 'facebook#get_all_credentials'
      get 'facebook/users/credentials/:account_id/:c_user_id', to: 'facebook#get_credentials'
      delete 'facebook/users/credentials/:account_id/:c_user_id', to: 'facebook#delete_credentials'
      get 'facebook/pages/credentials/:account_id', to: 'facebook#get_page_credentials'
      get 'facebook/pages/credentials/:account_id/:c_user_id', to: 'facebook#get_page_credentials_by_user'
      delete 'facebook/pages/credentials/:account_id/:fb_id', to: 'facebook#delete_page_credentials'
      get 'facebook/pages/read_wall/:account_id/:fb_id', to: 'facebook#read_wall'
      get 'facebook/pages/read_wall_comments/:account_id/:fb_id', to: 'facebook#read_wall_comments'
      delete 'facebook/pages/posts/:account_id/:fb_id/:post_id', to: 'facebook#delete_post'
      post 'facebook/pages/posts/comment', to: 'facebook#post_comment'
      post 'facebook/pages/comments/reply', to: 'facebook#reply_to_comment'
      delete 'facebook/pages/comments/:account_id/:fb_id/:comment_id', to: 'facebook#delete_comment'
      get 'rankings/:id' => 'rankings#index'
      get 'reviewers/:id/reviews' => 'reviewers#reviewer_reviews'
      get 'reviewers/:id' => "reviewers#show"
      get 'reviews/:account_id/:organization_id' => 'reviews#show'
      resources :content_providers
      resources :geocomps
resources :contents  
    get 'sentiments/languages' => 'sentiments#languages'
      get 'sentiments/:lang/:body' => 'sentiments#show'
      get 'senti/positive' => 'senti#positive'
      get 'senti/negative' => 'senti#negative'
      get 'senti/neutral' => 'senti#neutral'
      post 'senti/classify' => 'senti#classify'
      post 'senti/train' => 'senti#train'
      post 'senti/untrain' => 'senti#untrain'
      post 'sentiments' => 'sentiments#complex'
      post 'behavior/classify' => 'behavior#classify'
      post 'behavior/train' => 'behavior#train'
      post 'behavior/untrain' => 'behavior#untrain'
      get 'tracks' => 'tracks#index'
      get 'tracks/:keyword_id/facebook' => 'tracks#facebook'
      get 'tracks/:keyword_id/youtube' => 'tracks#youtube'
      get 'tracks/:keyword_id/instagram' => 'tracks#instagram'
      get 'tracks/:keyword_id/search/:market' => 'tracks#search'
      get 'tracks/:keyword_id/twitter' => 'tracks#twitter'

      resources :schedules
      # post 'keywords/:account_id/:keyword' => 'keywords#create_for_account'
      # post 'keywords/:acc/:org/:keyword' => 'keywords#create'
      post 'keywords/:account_id' => 'keywords#create_for_account'
      #post 'keywords/:acc/:org/' => 'keywords#create'
      delete 'keywords/:acc/:org/:keyword_id' => 'keywords#delete_association'
      get 'keywords/:acc/' => 'keywords#keywords_by_account'
      get 'keywords/refresh/:keyword_id' => 'keywords#refresh_aggregates'
      get 'keywords/:acc/:org' => 'keywords#index'
      get 'links/:acc/:org' => 'links#index'
      get 'markets' => 'markets#index'
      resources :instagram
      get 'google_plus/people/search/:p' => 'google_plus#people_search'
      #get 'google_plus/:acc/people/search/:p' => 'google_plus#people_search'
      get 'google_plus/people/:id/track' => 'google_plus#people_track'
      get 'google_plus/people/:id/activities' => 'google_plus#people_activities'
      get 'google_plus/people/:id/untrack' => 'google_plus#people_untrack'
      get 'google_plus/activity/:id/plusones' => 'google_plus#activity_plusones'
      get 'google_plus/activity/:id/reshares' => 'google_plus#activity_reshares'
      get 'google_plus/activity/:id/comments' => 'google_plus#activity_comments'
      resources :google
      get 'twitter/app/credentials' => 'twitter#get_app_credentials'
      post 'twitter/app/credentials' => 'twitter#set_app_credentials'
      delete 'twitter/app/credentials' => 'twitter#delete_app_credentials'
      put 'twitter/app/credentials' => 'twitter#update_app_credentials'
      post 'twitter/tweet' => 'twitter#tweet'
      post 'twitter/credentials' => 'twitter#set_credentials'
      get 'twitter/user/:user_id/tweets' => 'twitter#user_tweets'
      get 'twitter/search/:search' => 'twitter#tweet_search'
      get 'twitter/followers_average' => 'twitter#followers_average'
      get 'twitter/followers_count' => 'twitter#followers_count'
      get 'twitter/users_count' => 'twitter#users_count'
      get 'twitter/newest' => 'twitter#newest'
      get 'twitter/timeline/:c_user_id' => 'twitter#read_timeline'
      resources :twitter #wrap apphera twitter API
    
      resources :apps, only: %i[index]
    end
  end
end

app/views/layouts/frontpage/_carousel.html.erb
<div id='inSlider' class='carousel carousel-fade' data-ride='carousel'>
  <ol class='carousel-indicators'>
    <li data-target='#inSlider' data-slide-to='0' class='active'></li>
    <li data-target='#inSlider' data-slide-to='1'></li>
  </ol>
  <div class='carousel-inner' role='listbox'>
    <div class='item active'>
      <div class='container'>
        <div class='carousel-caption'>
          <h1>
            AI Driven Chat Bots<br/>that train your employees<br/>
            in Cyber Security<br/>
          </h1>
          <p>Raising Security Awareness</p>
          <p>
            <a href='mailto:info@hawkmatrix.com' class='btn btn-primary'>Email Us For Test Drive</a>
          </p>
        </div>
        <div class='carousel-image wow zoomIn'>
          <%= image_tag('landing/laptop.png', alt: 'laptop')%>
        </div>
      </div>
      <div class='header-back one'></div>
    </div>
    <div class='item'>
      <div class='container'>
        <div class='carousel-caption blank'>
          <h1>Chat based <br/> security training for your employees.</h1>
          <p>Available via Skype, slack, facebook and other platforms.</p>
          <a href='mailto:info@hawkmatrix.com' class='btn btn-primary'>Email Us For Test Drive</a>
        </div>
      </div>
      <!-- Set background for slide in css -->
      <div class='header-back two'></div>
    </div>
  </div>
  <a class='carousel-control left' href='#inSlider' role='button' data-slide='prev'>
    <span class='glyphicon glyphicon-chevron-left' aria-hidden='true'></span>
    <span class='sr-only'>Previous</span>
  </a>
  <a class='carousel-control right' href='#inSlider' role='button' data-slide='next'>
    <span class='glyphicon glyphicon-chevron-right' aria-hidden='true'></span>
    <span class='sr-only'>Next</span>
  </a>
</div>

app/views/layouts/frontpage/_contact.html.erb
<section id="contact" class="gray-section contact">
  <div class="container">
    <div class="row m-b-lg">
      <div class="col-lg-12 text-center">
        <div class="navy-line"></div>
        <h1>Contact Us</h1>
        <a href="mailto:info@hawkmatrix.com    " class="btn btn-primary">Email Us</a>
      </div>
    </div>
    <div class="row m-b-lg">
      <div class="col-lg-3 col-lg-offset-3">
        <address>
          <strong><span class="navy">HawkMatrix, Inc.</span></strong><br/>
          8736 Production Ave. Suite B<br/>
          San Diego, CA 92121<br/>
          <abbr title="Phone">P:</abbr> +1(858) 877-6554
        </address>
      </div>
      <div class="col-lg-4">
        <p class="text-color">
          Cyber Security Training via Chat.
        </p>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12 text-center">
        <a href="mailto:info@hawkmatrix.com    " class="btn btn-primary">Email Us</a>
        <p class="m-t-sm">
          <script src="//platform.linkedin.com/in.js" type="text/javascript"> lang: en_US</script>
          <script type="IN/FollowCompany" data-id="6405033" data-counter="right"></script>
        </p>
        <ul class="list-inline social-icon">
          <li>
            <a href="https://twitter.com/hawkmatrix" target="_blank" >
              <i class="fa fa-twitter"></i>
            </a>
          </li>
        </ul>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 text-center m-t-lg m-b-lg">
        <p><strong>&copy; 2015 - 2017 HawkMatrix, Inc., Patent pending technology</strong><br/> </p>
      </div>
    </div>
  </div>
</section>

app/views/layouts/frontpage/_features.html.erb
<section  class="container features">
  <div class="row">
    <div class="col-lg-12 text-center">
      <div class="navy-line"></div>
      <h1>
      	Raise the security awareness of your people.<br/>
      	<span class="navy"> Create a stronger cyber defense!</span>
      </h1>
      <p>
      	The press is filled with reports about high profile cyber attacks via spear phishing, social engineering and other ways to exploit your employees. Don't be the next victim, make your people the strongest link in your security strategy. <br />
			</p>
    </div>
  </div>
</section>

app/views/layouts/frontpage/_header.html.erb
<div class='navbar-wrapper'>
  <nav class='navbar navbar-default navbar-fixed-top navbar-scroll' role='navigation'>
    <div class='container'>
      <div class='navbar-header page-scroll'>
        <button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='#navbar' aria-expanded='false' aria-controls='navbar'>
          <span class='sr-only'>Toggle navigation</span>
          <span class='icon-bar'></span>
          <span class='icon-bar'></span>
          <span class='icon-bar'></span>
        </button>
        <a class='navbar-brand' href='/'>EQBotics</a>
      </div>
      <div id='navbar' class='navbar-collapse collapse'>
        <ul class='nav navbar-nav navbar-right'>
          <li><a class='page-scroll' href='#page-top'>Home</a></li>
          <li><a class='page-scroll' href='#features'>Features</a></li>
          <li><a class='page-scroll' href='#team'>Team</a></li>
          <li><a class='page-scroll' href='#testimonials'>Testimonials</a></li>
          <li><a class='page-scroll' href='#pricing'>Pricing</a></li>
          <li><a class='page-scroll' href='#contact'>Contact</a></li>
          <% if current_user.present? %>
            <li><%= link_to 'Dashboard', dashboard_path, class: 'page-scroll' %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, class: 'page-scroll', method: :delete %></li>
          <% else %>
            <li><%= link_to 'Sign In', new_user_session_path, class: 'page-scroll' %></li>
            <li><%= link_to 'Sign Up', new_user_registration_path, class: 'page-scroll' %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/frontpage/_pricing.html.erb
<section id="pricing" class="pricing">
  <div class="container">
    <div class="row m-b-lg">
      <div class="col-lg-12 text-center">
        <div class="navy-line"></div>
        <h1>App Pricing</h1>
        <p>Simple pay as you go pricing without hidden clauses.</p>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12 wow zoomIn">
        <ul class="pricing-plan list-unstyled selected">
          <li class="pricing-title">Best Option;-) </li>
          <li class="pricing-desc"> One Simple per seat fee. </li>
          <li class="pricing-price"> <span>$5</span> / seat / month </li>
          <li> $100 per month minimum. </li>
          <li class="plan-action">
            <a class="btn btn-primary btn-xs" href="http://www.hawkmatrix.com/users/sign_up">Signup</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</section>

app/views/layouts/frontpage/_services.html.erb
<section id="features" class="container services">
  <div class="row">
    <div class="col-sm-3">
      <h2>CYBER CRIME PREVENTION</h2>
      <p>Train your employees via Skype/Office365 Teams/Facebook Messenger or Slack!</p>
    </div>
    <div class="col-sm-3">
      <h2>Gamified!</h2>
      <p>To increase the success of the training the whole platform is gamified. Your employees gain points and badgdes for their learning progress.</p>
    </div>
    <div class="col-sm-3">
      <h2>Security Overview</h2>
      <p>The system creates an overview about the level of knowledge in your organization. Learn about your readiness.</p>
    </div>
    <div class="col-sm-3">
      <h2>Non intrusive training</h2>
      <p>No more scheduling boring lenghty seminars for your employees but just minutes a day in a familar chat environment.</p>
    </div>
  </div>
</section>

app/views/layouts/frontpage/_team.html.erb
<section id='team' class='gray-section team'>
  <div class='container'>

    <div class='row m-b-lg'>
      <div class='col-lg-12 text-center'>
        <div class='navy-line'></div>
        <h1>Our Team</h1>
        <p>There is no 'i' in team but there is in win.</p>
        <hr />
      </div>
    </div>

    <div class='row'>

      <div class='col-sm-4 wow fadeInLeft'>
        <div class='team-member'>
          <img src='http://hawkmatrix.azurewebsites.net/img/kate.jpg' class='img-responsive img-circle img-small' alt=''>
          <h4><span class='navy'>Katerina</span> Archangorodskaja</h4>
          <p>President and CEO</p>
          <ul class='list-inline social-icon'>
            <li>
              <a href='https://www.linkedin.com/in/intelligentperfection' target='_blank' >
                <i class='fa fa-linkedin'></i>
              </a>
            </li>
          </ul>
        </div>
      </div>

      <div class='col-sm-4'>
        <div class='team-member wow zoomIn'>
          <%= image_tag('http://hawkmatrix.azurewebsites.net/img/mashallah.jpg', class: 'img-responsive img-circle img-small') %>
          <h4><span class='navy'>Mashallah</span> Afshar</h4>
          <p>CFO</p>
          <ul class='list-inline social-icon'>
            <li>
              <a href='https://www.linkedin.com/pub/mashallah-afshar/2a/682/27' target='_blank' >
                <i class='fa fa-linkedin'></i>
              </a>
            </li>
          </ul>
        </div>
      </div>

      <div class='col-sm-4 wow fadeInRight'>
        <div class='team-member'>
          <%= image_tag('http://hawkmatrix.azurewebsites.net/img/thorsten.jpg', class: 'img-responsive img-circle img-small') %>
          <h4><span class='navy'>Thorsten</span> Weber</h4>
          <p>COO</p>
          <ul class='list-inline social-icon'>
            <li>
              <a href='https://de.linkedin.com/pub/thorsten-weber/1/233/930' target='_blank' >
                <i class='fa fa-linkedin'></i>
              </a>
            </li>
          </ul>
        </div>
      </div>

    </div>

    <div class='row'>

      <div class='col-sm-4 wow fadeInLeft'>
        <div class='team-member'>
          <%= image_tag('http://hawkmatrix.azurewebsites.net/img/avatar3.jpg', class: 'img-responsive img-circle img-small') %>
          <h4><span class='navy'>Nikolai</span> Manek</h4>
          <p>Chairman & CTO</p>
          <ul class='list-inline social-icon'>
            <li>
              <a href='https://twitter.com/nikolaimanek' target='_blank' >
                <i class='fa fa-twitter'></i>
              </a>
            </li>
            <li>
              <a href='https://www.linkedin.com/in/nikolaimanek'>
                <i class='fa fa-linkedin'></i>
              </a>
            </li>
          </ul>
        </div>
      </div>

      <div class='col-sm-4'>
        <div class='team-member wow zoomIn'>
          <%= image_tag('http://hawkmatrix.azurewebsites.net/img/takumi.jpg', class: 'img-responsive img-circle img-small') %>
          <h4><span class='navy'>Takumi Brian</span> Abe</h4>
          <p>Executive VP Customer Relations</p>
          <ul class='list-inline social-icon'>
            <li>
              <a href='https://www.linkedin.com/pub/takumi-brian-abe/87/559/863' target='_blank' >
                <i class='fa fa-linkedin'></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
      <hr />
      <div class='row m-b-lg'>
        <div class='col-lg-12 text-center'>
          <div class='navy-line'></div>
          <h1>Our Advisory Board</h1>
          <p>Great mentorship is priceless.</p>
          <hr />
        </div>
      </div>

    </div>

    <div class='row'>
      <div class='col-sm-4 wow fadeInLeft'>
        <div class='team-member'>
          <%= image_tag('http://hawkmatrix.azurewebsites.net/img/peter.jpg', class: 'img-responsive img-circle img-small') %>
          <h4><span class='navy'>Peter E.</span> Michel</h4>
          <p>
            13 Years CEO at Brink’s security and several other C level positions.
            Executive Program in Strategy and Organization, Stanford University.
            MA, public administration, University of Virginia. BA, political science, Colgate University.
            Hall of Fame for distinguished industry service SECURITY SALES AND MARKETING - 2003
            Hope Award MULTIPLE SCLEROSIS SOCIETY, LONE STAR CHAPTER - 2001
            President's Award
            SECURITY INDUSTRY ASSOCIATION - 2001
          </p>
          <ul class='list-inline social-icon'>
            <li>
              <a href='https://www.linkedin.com/pub/peter-michel/3/813/704' target='_blank' >
                <i class='fa fa-linkedin'></i>
              </a>
            </li>
          </ul>
        </div>
      </div>

      <div class='col-sm-4'>
        <div class='team-member wow zoomIn'>
          <%= image_tag('http://hawkmatrix.azurewebsites.net/img/longin.jpg', class: 'img-responsive img-circle img-small') %>
          <h4><span class='navy'>Prof. Dr. Longin Jan</span> Latecki</h4>
          <p>Mathematician. Winner of the International Pattern Recognition Award, Olympus Price Winner, Editorial Board of Pattern Recognition (PR), Editorial Board of Computer Vision and Image Understanding (CVIU), Editorial Board of Journal of Mathematical Imaging and Vision (JMIV), Chair of PhD Track in Artificial Intelligence, Chair of Future of Computing Competition 2008-2012</p>
        </div>
      </div>

      <div class='col-sm-4 wow fadeInRight'>
        <div class='team-member'>
          <%= image_tag('http://hawkmatrix.azurewebsites.net/img/kurt.jpg', class: 'img-responsive img-circle img-small') %>
          <h4><span class='navy'>Kurt-Juergen</span> Schimmelpfeng</h4>
          <p>Attorney of Law, former Managing Director of the VHSp (Association of Hamburg’s/Germany logics companies), DIHS GmbH, Member of the Supervisory Board of Dakosy AG, Managing Director of the Academy of Logistics in Hamburg, Germany </p>
          <ul class='list-inline social-icon'>
            <li>
              <a href='https://de.linkedin.com/pub/kurt-juergen-schimmelpfeng/a8/9/b7/en' target='_blank' >
                <i class='fa fa-linkedin'></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div class='row'>
      <div class='col-sm-4 wow fadeInLeft'>
        <div class='team-member'>
          <%= image_tag('http://hawkmatrix.azurewebsites.net/img/mashallah.jpg', class: 'img-responsive img-circle img-small') %>
          <h4><span class='navy'>Marshallah</span> Afshar, MBA</h4>
          <p>CPA, MBA, More than 30 years accounting and tax experience in the USA, CEO of Parsfinancials, Inc.</p>
          <ul class='list-inline social-icon'>
            <li>
              <a href='https://www.linkedin.com/pub/mashallah-afshar/2a/682/27' target='_blank' >
                <i class='fa fa-linkedin'></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
      <div class='col-sm-4'>
        <div class='team-member wow zoomIn'>
          <%= image_tag('http://hawkmatrix.azurewebsites.net/img/alex.jpeg', class: 'img-responsive img-circle img-small') %>
          <h4><span class='navy'>Alejandro V.</span> Natividad, MD</h4>
          <p>MD, Psychiatrist, Medical Director of Hospital in Texas since 1998, Inventor of Neuroscience based Security</p>
          <ul class='list-inline social-icon'>
            <li>
              <a href='https://www.linkedin.com/pub/alex-natividad-md/56/925/b31' target='_blank' >
                <i class='fa fa-linkedin'></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
      <div class='col-sm-4 wow fadeInRight'>
        <div class='team-member'>
          <%= image_tag('http://hawkmatrix.azurewebsites.net/img/erik.jpg', class: 'img-responsive img-circle img-small')%>
          <h4><span class='navy'>Erik</span> Hemmi, BA</h4>
          <p>BA Economics, 17 years sales experience, expert in direct and channel sales at CISCO SYSTEMS (previous major accounts at PAYCHEX and ADP). Top 10 producer in 5 consecutive years, sales trainer and responsible for southern California San Diego and Orange County.</p>
          <ul class='list-inline social-icon'>
            <li>
              <a href='https://www.linkedin.com/pub/erik-hemmi/b/817/5a0' target='_blank' >
                <i class='fa fa-linkedin'></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class='row'>
      <div class='col-sm-4 wow fadeInLeft'>
        <div class='team-member'>
          <%= image_tag('http://hawkmatrix.azurewebsites.net/img/david.jpg', class: 'img-responsive img-circle img-small') %>
          <h4><span class='navy'>David</span> Froman</h4>
          <p>Attorney of Law at Froman Law Firm, Commander Fighter U.S. Navy, LL.M. International Law, Harvard Law School - B.A. Mathematics, Magna Cum Laude -  Southwestern College - J.D. Law, Cum Laude, San Diego School of Law</p>
          <ul class='list-inline social-icon'>
            <li>
              <a href='https://www.linkedin.com/pub/david-froman/1b/48/612' target='_blank' >
                <i class='fa fa-linkedin'></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class='row'></div>
  </div>
</section>

app/views/layouts/frontpage/_testimonials.html.erb
<section id='testimonials' class='navy-section testimonials' style='margin-top: 0'>
  <div class='container'>
    <div class='row'>
      <div class='col-lg-12 text-center wow zoomIn'>
        <i class='fa fa-comment big-icon'></i>
        <h1>What our users say</h1>
        <div class='testimonials-text'>
          <i>'Our entire industry has become more safe over night by rolling out HawkMatrix cyber security training to all of our 700 member companies'</i>
        </div>
        <small>
          <strong>Kurt-Juergen Schimmelpfeng, Attorney at law</strong>
        </small>
      </div>
    </div>
  </div>
</section>

app/views/layouts/frontpage/_timeline.html.erb
<section class="timeline gray-section">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <div class="navy-line"></div>
        <h1>How to start</h1>
        <p>Rolling out sophisticated security training within minutes accross your organization. </p>
      </div>
    </div>
    <div class="row features-block">
      <div class="col-lg-12">
        <div id="vertical-timeline" class="vertical-container light-timeline center-orientation">
          <div class="vertical-timeline-block">
            <div class="vertical-timeline-icon navy-bg">
              <i class="fa fa-briefcase"></i>
            </div>
            <div class="vertical-timeline-content">
              <h2>Signup</h2>
              <p>Contact us and signup with one of our trained agents.</p>
              <span class="vertical-date">
                Today <br/> <small><%= Date.today %></small>
              </span>
            </div>
          </div>

          <div class="vertical-timeline-block">
            <div class="vertical-timeline-icon navy-bg">
              <i class="fa fa-file-text"></i>
            </div>
            <div class="vertical-timeline-content">
              <h2>Provisioning</h2>
              <p>Within one week your organization is provisioned in the system and invitations for your employees are available.</p>
              <span class="vertical-date"> One Week <br/> <small><%= Date.today+7 %></small> </span>
            </div>
          </div>

          <div class="vertical-timeline-block">
            <div class="vertical-timeline-icon navy-bg">
              <i class="fa fa-cogs"></i>
            </div>
            <div class="vertical-timeline-content">
              <h2>Train</h2>
              <p>Within one day after activating their license your employees will be happily learn and quizzing away. </p>
              <span class="vertical-date"> One Day <br/> <small><%= Date.today+8 %></small> </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>